### ISSUE TITLE
A sugestion of adding a new paper "https://arxiv.org/abs/2307.14126"

### ISSUE THREAD

**Issue by billhhh** [han-liu/awesome-missing-modality-for-medical-images#1]
A awesome project! Thank you for organizing all these. Could you also add a new paper that from our team https://arxiv.org/abs/2307.14126 "Multi-modal Learning with Missing Modality via Shared-Specific Feature Modelling". It is open sourced  and the code is available at https://github.com/billhhh/ShaSpec

**Comment by han-liu** [comment]
Thank you for the suggestion. This paper was included in the table but the code was unavailable. The code status of this paper is now updated.

**Comment by billhhh** [comment]
Cool, thank you!
